-- Run this migration in the Supabase SQL Editor (or with the Supabase CLI)
-- before enabling the GitHub Actions workflow.

create table if not exists public.bank_accounts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  balance bigint not null default 0 check (balance >= 0),
  last_credit_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.credit_feng_brother_bank()
returns table (
  account_name text,
  balance bigint,
  last_credit_date date
)
language plpgsql
security definer
set search_path = public
as $$
declare
  taiwan_today date := (now() at time zone 'Asia/Taipei')::date;
begin
  -- A newly created account starts at NT$0. Marking today prevents the
  -- creation run from also receiving today's NT$33 credit.
  insert into public.bank_accounts (name, balance, last_credit_date)
  values ('鋒兄銀行', 0, taiwan_today)
  on conflict (name) do nothing;

  -- This condition makes retries and manual workflow runs idempotent for a day.
  update public.bank_accounts as account
  set
    balance = account.balance + 33,
    last_credit_date = taiwan_today,
    updated_at = now()
  where account.name = '鋒兄銀行'
    and account.last_credit_date is distinct from taiwan_today;

  return query
  select bank_accounts.name, bank_accounts.balance, bank_accounts.last_credit_date
  from public.bank_accounts
  where bank_accounts.name = '鋒兄銀行';
end;
$$;

-- Only the service-role key used by the scheduled workflow may invoke this.
revoke all on function public.credit_feng_brother_bank() from public, anon, authenticated;
grant execute on function public.credit_feng_brother_bank() to service_role;
